absolute_urls: false
reverse_proxy_setup: true

home:
  alias: '/syseleven-stack'

intl_enabled: true
languages:
  supported:
    - en
    - de
  include_default_lang: true
  translations: true
  translations_fallback: true
  session_store_active: true
  http_accept_language: true
  override_locale: false

pages:
  theme: learn2-syseleven
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    default: 'd-m-Y H:i'
    short: 'jS M Y'
    long: 'd-m-y G:i'
  markdown:
    extra: true
    auto_line_breaks: true
    auto_url_links: false
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
  process:
    markdown: true
    twig: false
  types:
    - txt
    - xml
    - html
    - htm
    - json
    - rss
    - atom
  ignore_files:
    - .DS_Store
  ignore_folders:
    - .git
    - .idea
  ignore_hidden: true
  url_taxonomy_filters: true
  redirect_default_code: '302'
  redirect_trailing_slash: true
  frontmatter:
    process_twig: false
    ignore_fields:
      - form
      - forms

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: false
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  releases: stable
  verify_peer: true
  official_gpm_only: true
