name: Check documentation
on:
  - push
jobs:
  Lint:
    name: Documentation Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: "npm install"
      - run: "npm run lint"
